### ISSUE TITLE
how can I get the network description and visualization?

### ISSUE THREAD

**Issue by sangthian** [peiyunh/tiny#2]
Hello, I am very interested in your job. firstly, I want to to see what the networ look like, just like prototxt file in Caffe. Thanks.

**Comment by peiyunh** [comment]
After you load the net into matlab, you should be able to see its description as a structure array. 

In terms of visualization, it gets a little bit trickier. Matconvnet has implemented [`model2dot.m`](https://github.com/peiyunh/matconvnet/blob/9822ec97f35cf5a56ae22707cc1c04e0d738e7db/utils/model2dot.m), which takes a net and export a [dot](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) file (similar to how Caffe does it). Since our model contains some new (but very simple) layers, you may have to modify the original `model2dot.m` to make it work with our structure.

**Comment by Cv9527** [comment]
would you release the training code for the academic goal?

**Comment by peiyunh** [comment]
I will release training code soon.
