### ISSUE TITLE
How to add layers of different scale

### ISSUE THREAD

**Issue by nopattern** [peiyunh/tiny#3]
Thank you for your good job .
   There is Res4+Res3+Res2 in your article . They are in different scale . How to add them together in your paper?

**Comment by peiyunh** [comment]
We interpolate the prediction from res4 up to the scale of res3, then sum them up. We do so from res3 to res2 as well. Such process is well explained in this paper: https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf.

**Comment by nopattern** [comment]
Thank  you for clarification. Will be a deconvolution better?

**Comment by peiyunh** [comment]
@nopattern We implement such interpolation through deconvolution with fixed weights.

**Comment by nopattern** [comment]
got it. Thank you .

**Comment by marvis** [comment]
Hello Peiyun Hu,

I am very confused by the explanation of fusing Res4+Res3+Res2.
I find your network description from http://ethereon.github.io/netscope/#/gist/8a0d5ef37da9dc4cd611d178404b3641.  In this network, you only fused the score of res3 and res4 instead of res2.  Did I understand correctly?

Best

**Comment by peiyunh** [comment]
Hi @marvis, the released model only has res4+res3, as it performs similarly to res4+res3+res2 while being a little more efficient during inference.

**Comment by marvis** [comment]
Got it. Great thanks！
