### ISSUE TITLE
what can cause memory problems?

### ISSUE THREAD

**Issue by zzw1123** [peiyunh/tiny#41]
thanks for the code which really helps me a lot!!
but a warning occurs while the demo is running,it is as follows:

Warning: print2array generating a 168.1M pixel image. This could be slow and might also cause memory problems. 
  > In print2array at 70
  > In export_fig at 516
  >In tiny_face_detector at 201
  >In demo_video at 11 

and the speed is very slow which is about 8 seconds per image,so i wonder if it is the command "export_fig" that cause memory problems? and how should i solve it???
i want to save every image after i run the demo without display it on my screen , can anyone tell me what command should i add ?
thanks a lot!!!

**Comment by peiyunh** [comment]
The memory issue is likely due to a very high resolution input image. You may want to try a lower DPI when calling export_fig ( https://github.com/peiyunh/tiny/blob/master/tiny_face_detector.m#L197 ), such as  

`export_fig('-dpng', '-native', '-opengl', '-transparent', output_path, '-r300');`

to 

`export_fig('-dpng', '-native', '-opengl', '-transparent', output_path, '-r100');`

This will print a much lower-resolution output, which requires less memory.

**Comment by zzw1123** [comment]
@peiyunh alright，I will try it,thanks!
