### ISSUE TITLE
Questions on cnn_add_loss_fcn8s_resnet101_simple.m

### ISSUE THREAD

**Issue by yxchng** [peiyunh/tiny#43]
```
% adapt for different input sizes (we end up using 500x500)
if all(opts.inputSize==500)
    ctblk = dagnn.ConvTranspose('size', size(filter), 'upsample', 2, ...
                                'crop', [1,2,1,2], 'hasBias', false);
```
1. Can I know where do you use 500x500 size image? In the demo, you seem to be using images of different scales and not 500x500. 
2. Also, isn't the input image for resnet101 224x224? Why is it stated as 500x500 here?
3. How does the crop being [1,2,1,2] work? From this visualization http://ethereon.github.io/netscope/#/gist/8a0d5ef37da9dc4cd611d178404b3641, the crop goes from 30x30 to 28x28. This code seems to suggest that it will crop the image to 27x27?

**Comment by peiyunh** [comment]
1. Our network was trained on random crops from input images. 500x500 means the crop size. 
2. Once you make ResNet101 fully convolutional, you can apply it on images that are larger than 224x224. Also note that, we use a truncated version of ResNet. 
3. We pick [1,2,1,2] because it can make sure the dimension of intermediate activations align with each other when we sum them up. I am not sure if I understand your second question. As far as I know, the visualization tool is based on Caffe's implementation, which may be slightly different comparing to MatConvNet, especially on spatial pooling.
